-
 
 name: host listing
 hosts: appserver
 gather_facts: no
 tasks:
   - 
     name: Checking For Docker 
     yum: 
       list: docker
     register: docker_list 
   -
     name: installing docker to appserver.
     yum:
      name=docker
      state=present
     register: installed_docker
   - 
     name: Installing Epel-Release For pip
     yum:
       name=epel-release
       state=present
     register: installed_epel
     ignore_errors: true
   
   
   - 
     name: Starting docker
     service: 
      name: docker
      state: started
      enabled: yes
     ignore_errors: true
   -
     name: Checking For Python
     command: which python
     register: python_absent
     ignore_errors: true
   -
     name: Installing Python
     yum:
       name=python
       state=present
     when: python_absent.rc==1
     register: python_installed

   - 
     name: checkin Whether pip is available or not
     command: which pip
     register: pip_absent
     ignore_errors: true
   
   - 
     name: Installing Pip 
     yum:
       name=python-pip
       state=present 
     when: pip_absent.rc==1
     register: installed_pip
     

   - 
      name: Installing docker-py
      pip:
       name: docker
       state: present
      register: dockerpy_installed
  
   - 
     name: Docker Network Creation 
     docker_network:
            name: linknet 
     register: network created
     ignore_errors: true

     
   - 
     name: Starting Mysql Container
     docker_container:
                name: db
                image: mysql
                networks: 
                   - name: linknet
                ports:
                 - 3306:3306
                env:
                 MYSQL_ROOT_PASSWORD: root
                detach: true 
     register: mysql_container

   - 

      name: Wait Before Creating New Container
      command: sleep 60
                      
   - 
      name: Starting Media Wiki Container 
      docker_container: 
                  name: media
                  image: mediawiki
                  ports:
                    - 8080:80
                  networks:
                     - name: linknet 
                  links: db
                  detach: true 
      register: media_container
   -

      name: Waiting For MySQL host - delay 300sec
      command: sleep 300
   -  
      name: Configuring Mysql
      command: docker exec db mysql -uroot -proot -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password by 'root';"
      register: config_mysql1.changed
   -  
      name: Configuring Mysql
      command: docker exec db mysql -uroot -proot -e "ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password by 'root';"
      register: config_mysql2.changed

   -
      name: Checking if Database Exists
      command: docker exec db mysql -uroot -proot -e "show databases like 'my_wiki';"
      register: database_search
   -  
      name: Creating Database
      command: docker exec db mysql -uroot -proot -e "CREATE DATABASE my_wiki"
      register: database_created
      when: database_search.stdout==""
      
   
   -
      name: Display Info of Mysql
      shell: "docker inspect --format='{''{ .Config.Env}''}' db"
      register: db_output

   - 
      debug:
         var: "db_output.stdout"
   
